version: '3.9'
services:
  jobmanager:
    image: flink:latest
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    command: jobmanager

  taskmanager:
    image: flink:latest
    hostname: taskmanager
    environment:
      - "FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager"
    depends_on:
      - jobmanager 
    scale: 3
    command: taskmanager